[deps]
AirspeedVelocity = "1c8270ee-6884-45cc-9545-60fa71ec23e4"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Divergences = "7f07e4c8-6df2-5971-ad44-bf349b9adcfd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[sources]
Divergences = {path = ".."}

[compat]
AirspeedVelocity = "0.6"
BenchmarkTools = "1"
StableRNGs = "1"
