name = "Divergences"
uuid = "7f07e4c8-6df2-5971-ad44-bf349b9adcfd"
version = "0.4.2"
author = "Giuseppe Ragusa <giuseppe.ragusa@gmail.com>"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Aqua = "0.8"
BenchmarkTools = "1.6.3"
Distances = "0.10.12"
ForwardDiff = "0.10"
LaTeXStrings = "1.4.0"
NaNMath = "^1"
RecipesBase = "1.3"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ForwardDiff", "Test"]
